//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFLCalc.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFLCalc.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        internal static string Calculate_text {
            get {
                return ResourceManager.GetString("Calculate_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%h} h. {0:%m} min..
        /// </summary>
        internal static string Duration_hm_text {
            get {
                return ResourceManager.GetString("Duration_hm_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:%m} min..
        /// </summary>
        internal static string Duration_m_text {
            get {
                return ResourceManager.GetString("Duration_m_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Marathon.
        /// </summary>
        internal static string HMarathon_text {
            get {
                return ResourceManager.GetString("HMarathon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can run.
        /// </summary>
        internal static string I_can_run_text {
            get {
                return ResourceManager.GetString("I_can_run_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will try to run {0} km until the Catcher Car overtakes me..
        /// </summary>
        internal static string I_will_try_to_run_text {
            get {
                return ResourceManager.GetString("I_will_try_to_run_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string In_text {
            get {
                return ResourceManager.GetString("In_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marathon.
        /// </summary>
        internal static string Marathon_text {
            get {
                return ResourceManager.GetString("Marathon_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My VDOT is.
        /// </summary>
        internal static string My_vdot_is_text {
            get {
                return ResourceManager.GetString("My_vdot_is_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace: {0:m\:ss} min/km..
        /// </summary>
        internal static string Pace_text {
            get {
                return ResourceManager.GetString("Pace_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time on distance: {0}.
        /// </summary>
        internal static string Time_on_distance_text {
            get {
                return ResourceManager.GetString("Time_on_distance_text", resourceCulture);
            }
        }
    }
}
